config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get :about,        to: 'static_pages#about'
  get :use_of_terms, to: 'static_pages#terms'
  get :signup,       to: 'users#new'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'
  resources :relationships, only: [:create, :destroy]
  get :favorites, to: 'favorites#index'
  post   "favorites/:post_id/create"  => "favorites#create"
  delete "favorites/:post_id/destroy" => "favorites#destroy"
  resources :comments, only: [:create, :destroy]
  resources :notifications, only: :index
  get :lists, to: 'lists#index'
  post   "lists/:post_id/create"  => "lists#create"
  delete "lists/:list_id/destroy" => "lists#destroy"
  resources :logs, only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @feed_items = current_user.feed.paginate(page: params[:page], per_page: 5)
      @log = Log.new
    end
  end

  def about
  end

  def terms
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "カフェログとは？") %>
<div id="fh5co-about">
  <div class="container">
    <h1>カフェログとは？</h1>
  </div>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div id="fh5co-portfolio">
    <div class="container">
      <div class="col-md-9">
        <h3>カフェリスト (<%= @feed_items.count %>)</h3>
        <%= render 'shared/feed' %>
      </div>
      <div class="col-md-3">
        <p><%= link_to "NEW", new_post_path, class: "btn btn-primary btn-lg btn-demo btn-record" %></p>
        <br>
        <p><%= link_to "CSV", "#", class: "btn btn-primary btn-lg btn-demo btn-csv" %></p>
      </div>
    </div>
  </div>
<% else %>
  <div class="page-header-image" data-parallax="true" style="background-image:url('/images/header_logo.jpg');">
    <header id="fh5co-header" class="fh5co-cover js-fullheight" role="banner">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-md-offset-2 text-center">
            <div class="display-t js-fullheight">
              <div class="display-tc js-fullheight animate-box" data-animate-effect="fadeIn">
                <h1>カフェログへようこそ！</h1>
                <p>行きたいお店、もう迷わない！</p>
                <p>
                  <%= link_to 'カフェログを始める', signup_path, class: "btn btn-primary btn-lg btn-demo" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
  </div>
<% end %>

app/views/static_pages/terms.html.erb
<% provide(:title, "利用規約") %>
<div id="fh5co-about">
  <div class="container">
    <h1>利用規約</h1>
  </div>
</div>